application: tinywebdbg54ubi
version: 2
runtime: python
api_version: 1

handlers:
- url: /images
  static_dir: images

- url: /jsclient
  static_dir: jsclient

- url: .*
  script: main.py



